devopsPath=devops/jenkins
mvnSetFile=settings-new.xml
mvnSecSetFile=settings-security.xml
mvnPomFile=pom-new.xml
utilPropsFile=remote-new.yml
instanceShell=ctrl.sh
releaseDir=/home/jenkins/data/release
holdData=portal
validPlatform=widget
validEnv=dev

isType=war
wasDocs=/jboss/applications
instDocs=/jboss/domains