
SERVER_NAME = LOCAL

#PRX - START
juso.interface.server = http://www.juso.go.kr/addrlink/addrLinkApi.do
juso.coord.key = U01TX0FVVEgyMDIxMDcyNzIwMTExMTExMTQ1OTg=
juso.key = U01TX0FVVEgyMDE2MDIyMzEwMTQ1MDA=

OCR.license=vNxBjN4e9s4F1jnf
OCR.server1=http://10.20.28.38:8111
OCR.server2=http://10.20.28.38:8112
OCRIMG.server=http://211.253.137.11:9628

OCREID.license=NQFAu84ckmeD0e9a
OCREID.server1=http://10.20.28.38:8201
OCREID.server2=http://10.20.28.38:8201

#inf.url as-is
#inf.url = http://112.175.98.116:8180
#inf.url HA-PROXY(STG)
inf.url = http://10.20.28.38:7006

# API server
api.interface.server = http://localhost:9380
#PRX - END

# MCP-API-EXT
ext.url = http://localhost:9195

sale.orgnId=1100011741

sale.sesplsOrgnId=V000019481

# SCAN
scan.app.path = C:/ktMmobile/workspace/ktmmobilemcp_dev/scan/
#scan.url = https://scndev.ktmmobile.com/webscan/interface/SCAN_ONLINEUPLOAD.jsp
scan.url = https://scnimgdev.ktmmobile.com/webscan/interface/SCAN_ONLINEUPLOAD.jsp
scan.V25.url = https://scnimgdev.ktmmobile.com/webscan/interface/SCAN_ONLINEUPLOAD.jsp
scan.V25.interface.url = https://scnimgdev.ktmmobile.com/webscan/interface.do
scan.path.urlTemp = C:/jboss/data/webscan/dev/image/URLTemp

# NICE
NICE_SITE_PASSWORD=F7LF8IPDD4VD
NICE_IPIN_SITE_PASSWORD=f7LF8IPD
NICE_UID_PASSWORD=Nktisc!@#

# NICE WEB API ACCOUNT OTP NAME
NICE_CLIENT_ID = 2997c467-b4d3-48e5-b367-70c62bada158
NICE_CLIENT_SECRET = d013126d839b697dc252952bdcd4d9b6

# NICE WEB API PASS
NICE_CLIENT_PASS_ID = 0a4fa3ed-e3e4-4311-af08-a18591924014
NICE_CLIENT_PASS_SECRET = b6e9f80d573576076efa1b4c7380d2bf

# TOSS
TOSS_SITE_URL=https://oauth2.cert.toss.im/token
TOSS_CLIENT_ID=c66ot3d8mau3ihqa5hs2typjad194uk9
TOSS_CLIENT_SECRET=ylEWG3xU2htLRUwKzUdNZQB8HOgCrkA2766DauKIGDKtIRkL

# NICE API
N_NICE_CLIENT_ID = dcc2d0ef-8ccc-4f2a-ba63-e664c9532d83
N_NICE_CLIENT_SECRET = ad49dfc17857638ccd0c3569d0f5e9f7

usim.selUsimIp = 14.49.31.194

# CTI
cti.url=http://ctidev.ktmmobile.com/ctiApp/reqServiceCall.do

#NAVER LOGIN
#NAVER_CLIENT_ID_NEW = S1P0a0Ru9XQdHtRtUz2F
#NAVER_CLIENT_SECRET_NEW = AwMaxDnC2N
NAVER_CLIENT_ID_NEW = Sjm326J_f9u7QI4jBcNm
NAVER_CLIENT_SECRET_NEW = jy97UAdwmw
NAVER_CALLBACK_URL = /login/naverCalbkUrl.do
NAVER_M_CALLBACK_URL = /m/login/naverCalbkUrl.do

NAVER_CLIENT_ID = Sjm326J_f9u7QI4jBcNm
NAVER_CLIENT_SECRET = jy97UAdwmw
NAVER_PC_CALLBACK_URL = /cert/naverCallBackPage.do
NAVER_MOBILE_CALLBACK_URL = /m/cert/naverCallBackPage.do
NAVER_PC_FAIL_CALLBACK_URL = /cert/naverFailPage.do
NAVER_MOBILE_FAIL_CALLBACK_URL = /m/cert/naverFailPage.do

# NEARO
NEARO_SERVICE_URL = http://localhost
NEARO_PC_CALLBACK_URL = /cert/nearoCallBack.do
NEARO_MOBILE_CALLBACK_URL = /m/cert/nearoCallBack.do
NEARO_PC_LOGIN_CALLBACK_URL = /cert/nearoCallBackLogin.do
NEARO_MOBILE_LOGIN_CALLBACK_URL = /m/cert/nearoCallBackLogin.do

# KAKAO LOGIN
KAKAO_AUTH_URL = https://kauth.kakao.com
KAKAO_API_KEY = 7d8419ffa95a82b20614aba64072187d
KAKAO_CALLBACK_URL = /login/kakaoCalbkUrl.do
KAKAO_M_CALLBACK_URL = /m/login/kakaoCalbkUrl.do

aes.app.aesLock = ZAdOYQIXSjC6FoTVr2hau2tS1pkKbzDvXCTbTJBnI2Q=

# SMARTRO
MERCHANTKEY=0/4GFsSd7ERVRGX9WHOzJ96GyeMTwvIaKSWUCKmN3fDklNRGw3CualCFoMPZaS99YiFGOuwtzTkrLo4bR4V+Ow==
# \uC6B4\uC601\uD0A4
#MERCHANTKEY=jdqtkHuD568a7NKyA2nlcMKlY94v2fsLhbe4VfEnGDIpkYwSCjz+mgKM1KKUGxYpZvZTes/6mGBo7ewUD+usIg==
MERCHANTKEY_N=0/4GFsSd7ERVRGX9WHOzJ96GyeMTwvIaKSWUCKmN3fDklNRGw3CualCFoMPZaS99YiFGOuwtzTkrLo4bR4V+Ow==
#\uCCAD\uAD6C\uD560\uC778 \uAC1C\uBC1C MID
MID=t_mmob001m
#\uC6B4\uC601MID
#MID=ktmmo0002m

#\uC989\uC2DC\uD560\uC778
MID_N=t_ktmo001m
MALL_IP = 127.0.0.1
SMARTRO_PC_RETURN_URL = https://local.portal.ktmmobile.com/smartro/returnPay.do
SMARTRO_MOBILE_RETURN_URL = https://local.portal.ktmmobile.com/m/smartro/returnPay.do
SMARTRO_REQ_SELF_STOP_URL = https://local.portal.ktmmobile.com/m/appForm/reqSelfDlvry.do
SMARTRO_RETRY_URL = https://local.portal.ktmmobile.com/appForm/inform.do
SMARTRO_CANCEL_URL = https://tapproval.smartropay.co.kr/payment/approval/cancel.do
SMARTRO_CANCEL_PW = 123456
SMARTRO_PC_SCRIPT_URL =  https://tpay.smartropay.co.kr/asset/js/SmartroPAY-1.0.min.js
SMARTRO_MOBILE_SCRIPT_URL = https://tmpay.smartropay.co.kr/asset/js/SmartroPAY-1.0.min.js
SMARTRO_APPROVAL_URL = https://tapproval.smartropay.co.kr/payment/approval/urlCallApproval.do



# file upolad
common.fileupload.base = C:/development/logs/upload
common.fileupload.web  = /resources/upload
common.fileupload.ext.denined = jsp,java,class,html,htm,js,php,php3,php4,asp,inc,pl,cgi,exe
common.fileupload.ext.images  = gif,png,bmp,jpg,jpeg,tiff
common.fileupload.size        = 30
common.fileupload.sellusim = C:/development/logs/uploadsellusim/
common.fileupload.report.size        = 10
common.fileupload.report =  C:/development/logs/upload/report

# file upload (msp)
common.fileupload.msp.base = C:/development/logs/images

#finace.end.imgPath =
#dongBuRate.org.imgPath =

# sms
sms.domain=ktmmobile.com
sms.eventcode=WEBAUTH
sms.callcenterold=18995000
sms.callcenter=18995000
sms.usim.rcptNo.old=01068642962,01032125599,01074043666,01032631833,01039498868,01056655680
sms.usim.rcptNo=01020075304,01032125599,01074043666,01032631833,01039498868,01056655680
sms.request.rcptNo=01025005882

#payInfo infomation
payInfo.end.imgPath = D\:/img/orgImg/ORIGIN_DIR/E0019/
payInfo.org.imgPath =  D\:/img/orgImg/payInfoDefaultImage.jpg
payInfo.org.fontPath =	D\:/img/orgImg/OnlineImageFont.ttf

# ELASTIC SEARCH
elastic.url=localhost

# audio captch wav file path
captcha.audio.wavPath =  /sounds/ko/numbers/

# APPLE LOGIN
apple.iss = https://appleid.apple.com
apple.team.id = 5YEXPKG7LM
apple.client.id = kt.co.ktmmobile.signin
apple.key.id = KW262ZB8LW
apple.pc.redirectUrl = /login/appleCalbkUrl.do
apple.mobile.redirectUrl = /m/login/appleCalbkUrl.do
apple.auth.url = https://appleid.apple.com
apple.auth.token.url = https://appleid.apple.com/auth/token
apple.publickey.url = https://appleid.apple.com/auth/keys
apple.cert.file = static/apple/AuthKey_KW262ZB8LW.p8

# kakao cert
kakao.url = https://test-apigates-pub.dozn.co.kr
kakao.apiKey = 7d8419ffa95a82b20614aba64072187d
kakao.sectKey = 1al6nLWTQ59dQTiWRQnx5Tn4Ci+ns02qJrtnbKiM4r8=
kakao.iv = LGzrSKS0D4D2JBchcOjDpg==

# recaptcha
recaptcha.sectKey = 6LctwxopAAAAAFWdicBWTJ_zTYwd64XxmcAyfDjp

# nicepin ci cert
ciPrx.siteCode = K406
ciPrx.sitePw = f7LF8IPD

# simpleAuth request URL
simpleAuth.nice.url = /nice/popNiceAuth.do
simpleAuth.pass.url = /nice/getPass.do
simpleAuth.kakao.url = /kakaoAuthPop.do
simpleAuth.toss.url = /nice/getToss.do

# mcash - DEV
mcash.main.url = http://btsoft-test.iptime.org:9443/mMob/caMain
mcash.inqCtgNo = 70011004
mcash.dspChnC = 007
mcash.aes256.key = hE4RO5UZdgXH2otBEass8kJcjHNbArzt
mcash.aes256.iv = HBvXuYPJF6d1TWhg

# mcash - PRD
#mcash.main.url = https://cashify.kr:9443/mMob/caMain
#mcash.inqCtgNo = 70011004
#mcash.dspChnC = 007
#mcash.aes256.key = YfexS1MhytcglhWM6pWT3Zu4FqjOxfhH
#mcash.aes256.iv = v5V0RbfEu4Xuqdjd

# MCP-ACEN-REQ (ext)
#acen.req.url = http://10.20.28.38:8251
# MCP-ACEN-REQ (req)
acen.req.url = http://10.20.28.38:8282


#JWT
jwt.pem.private.file=file:C:/development/private_pkcs8.pem
jwt.pem.public.file=file:C:/development/public.pem

#mstore
mstore.cert.url = https://stg-fo.benecafe.co.kr

