# M PLATFORM

#DEV - ITO
#juice.url=http://112.175.98.116:8180/mPlatform/serviceCall.do
#osst.url=http://112.175.98.116:8180/mPlatform/osstServiceCall.do
#osst.simple.open.url=http://112.175.98.116:8180/mPlatform/simpleOpenServiceCall.do


#PRX STG
#juice.url=http://10.20.28.38:7006/mPlatform/serviceCall.do
#osst.url=http://10.20.28.38:7006/mPlatform/osstServiceCall.do
#osst.simple.open.url=http://10.20.28.38:7006/mPlatform/simpleOpenServiceCall.do


juice.url=http://211.253.137.11:9627/mPlatform/serviceCall.do
osst.url=http://211.253.137.11:9627/mPlatform/osstServiceCall.do
osst.simple.open.url=http://211.253.137.11:9627/mPlatform/simpleOpenServiceCall.do

#juice.url=http://10.20.28.38:7006/mPlatform/serviceCall.do
#osst.url=http://10.20.28.38:7006/mPlatform/osstServiceCall.do
#osst.simple.open.url=http://10.20.28.38:7006/mPlatform/simpleOpenServiceCall.do
