// 부가기능 신청서
export const addFunction = {
  pages: [
    {
      ID: 'S105010101',
      화면명: '임시저장 목록',
      Depth1: '부가기능',
      Depth2: '임시저장',
      Depth3: '',
      PATH: '/extra/tempsave/TempSavePage',
      상태: 'completed',
      완료일: '2026-04-17',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S105020101',
      화면명: '접수완료 신청서 목록',
      Depth1: '부가기능',
      Depth2: '접수완료 신청서',
      Depth3: '',
      PATH: '/extra/receipt/ReceiptPage',
      상태: 'completed',
      완료일: '2026-04-17',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S105030101',
      화면명: '간편 신청서 목록',
      Depth1: '부가기능',
      Depth2: '간편 신청서',
      Depth3: '',
      PATH: '/extra/simplerequest/SimpleRequestPage',
      상태: 'completed',
      완료일: '2026-04-17',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S105040101',
      화면명: '로그인 설정',
      Depth1: '부가기능',
      Depth2: '로그인 설정',
      Depth3: '',
      PATH: '/setting',
      상태: 'completed',
      완료일: '2026-04-17',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S105040102',
      화면명: '지문 설정/해제',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
    {
      ID: 'S105040103',
      화면명: 'Face ID 설정/해제',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
  ],
}
export default addFunction
