// 기타
export const etc = {
  pages: [
    {
      ID: 'S106010101',
      화면명: '스마트 신청서 App 설치',
      Depth1: '기타',
      Depth2: '스마트 신청서 App 설치',
      Depth3: '',
      PATH: '/pub/S106010101',
      상태: 'completed',
      완료일: '2026-04-17',
      최종수정일: '',
      비고: '헤더, 하단베뉴 없는 레이아웃',
    },
    {
      ID: 'S106020101',
      화면명: 'App 로딩',
      Depth1: '기타',
      Depth2: 'App 로딩',
      Depth3: '',
      PATH: '/test',
      상태: 'completed',
      완료일: '2026-04-17',
      최종수정일: '',
      비고: 'MsfLoadingComp',
    },
    {
      ID: 'S106020102',
      화면명: 'App 유효성 체크 안내',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
    {
      ID: 'S106020103',
      화면명: 'App 접근 권한',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
    {
      ID: 'S106020104',
      화면명: 'App 업데이트',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
    {
      ID: 'S106030101',
      화면명: 'ID/PW 로그인',
      Depth1: '',
      Depth2: '기타',
      Depth3: '로그인',
      PATH: '/login',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S106030102',
      화면명: '지문 로그인',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
    {
      ID: 'S106030103',
      화면명: 'Face ID 로그인',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
    {
      ID: 'S106030104',
      화면명: '단말 사용 인증',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/deviceAuth',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S106030105',
      화면명: '단말 사용 등록',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/deviceRegist',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S106040101',
      화면명: '메인',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S106040102',
      화면명: '공지사항',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S106040103',
      화면명: 'Q&A',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S106040104',
      화면명: 'Q&A 등록',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S106050101',
      화면명: '안내',
      Depth1: '기타',
      Depth2: '안내',
      Depth3: '',
      PATH: '',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S106060101',
      화면명: '간편 신청서 정보 입력',
      Depth1: '기타',
      Depth2: '간편 신청서',
      Depth3: '',
      PATH: '',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '개발 여부 미확정',
    },
    {
      ID: 'S106060102',
      화면명: '통합인증',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '개발 여부 미확정',
    },
    {
      ID: 'S106060103',
      화면명: '약관 상세',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'waiting',
      완료일: '',
      최종수정일: '',
      비고: '개발 여부 미확정',
    },
  ],
}
export default etc
