// 명의변경 신청서
export const formOwnChg = {
  pages: [
    {
      ID: 'S103050101',
      화면명: '메인',
      Depth1: '명의변경 신청서',
      Depth2: '',
      Depth3: '',
      PATH: '/form/ownerchange',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S103010101',
      화면명: '고객',
      Depth1: '명의변경 신청서',
      Depth2: '고객',
      Depth3: '',
      PATH: '',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S103020101',
      화면명: '상품',
      Depth1: '명의변경 신청서',
      Depth2: '상품',
      Depth3: '',
      PATH: '',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S103030101',
      화면명: '동의',
      Depth1: '명의변경 신청서',
      Depth2: '동의',
      Depth3: '',
      PATH: '',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S103030103',
      화면명: '신청정보 확인',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'S101040104 와 동일',
    },
    {
      ID: 'S103040101',
      화면명: '신청완료',
      Depth1: '명의변경 신청서',
      Depth2: '신청완료',
      Depth3: '',
      PATH: '/pub/S101050101',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'S101050101 와 동일',
    },
  ],
}
export default formOwnChg
