// 서비스변경 신청서
export const formSvcChg = {
  pages: [
    {
      ID: 'S102010101',
      화면명: '메인',
      Depth1: '서비스변경 신청서',
      Depth2: '',
      Depth3: '',
      PATH: '/form/servicechange',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S102020101',
      화면명: '고객',
      Depth1: '서비스변경 신청서 > 고객',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S102030101',
      화면명: '상품',
      Depth1: '서비스변경 신청서 > 상품',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S102030102',
      화면명: '불법TM수신차단',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S102030103',
      화면명: '번호도용 차단 서비스',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S102030104',
      화면명: '(신)로밍 하루종일 ON',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S102030105',
      화면명: '사용요금 조회',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S102040101',
      화면명: '동의',
      Depth1: '서비스변경 신청서 > 동의',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'completed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S102040103',
      화면명: '신청정보 확인',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'removed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: 'S101040104 와 동일',
    },
    {
      ID: 'S102050101',
      화면명: '신청완료',
      Depth1: '서비스변경 신청서 > 신청완료',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/S101050101',
      상태: 'removed',
      완료일: '2026-04-03',
      최종수정일: '',
      비고: 'S101050101 와 동일',
    },
  ],
}
export default formSvcChg
