// 신규/변경 신청서
export const formNewChg = {
  pages: [
    {
      ID: 'S101010101',
      화면명: '메인',
      Depth1: '신규/변경 신청서',
      Depth2: '',
      Depth3: '',
      PATH: '/form/newchange',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S101010102',
      화면명: '예상 납부금액',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: 'MsfPrevPayCostPop',
    },
    {
      ID: 'S101020101',
      화면명: '고객',
      Depth1: '신규/변경 신청서 > 고객',
      Depth2: '',
      Depth3: '',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '2026-04-03',
      비고: '박스컴퍼넌트로 교체',
    },
    {
      ID: 'S101020109',
      화면명: '신분증 목록 조회',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S101020102',
      화면명: '신분증/서류 스캔',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
    {
      ID: 'S101020103',
      화면명: '모바일신분증 조회',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
    {
      ID: 'S101020104',
      화면명: '안면인증',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI – m플랫폼 연동',
    },
    {
      ID: 'S101020110',
      화면명: '구비서류',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '2026-04-03',
      비고: '플래그 추가',
    },
    {
      ID: 'S101020105',
      화면명: '사진 촬영',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
    {
      ID: 'S101020106',
      화면명: '우편번호 찾기 (주소찾기)',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '2026-03-31',
      비고: '페이징 간격수정',
    },
    {
      ID: 'S101020107',
      화면명: '약관 상세',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: '약관 컴퍼넌트 내장',
    },
    {
      ID: 'S101020108',
      화면명: '안내동의 상세',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S101030101',
      화면명: '상품',
      Depth1: '신규/변경 신청서 > 상품',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S101030102',
      화면명: 'USIM 스캔',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
    {
      ID: 'S101030103',
      화면명: 'eSIM 스캔샘플',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
    {
      ID: 'S101030107',
      화면명: '휴대폰 스캔',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - Android/iOS',
    },
    {
      ID: 'S101030104',
      화면명: '번호이동 사전동의 실패 안내',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S101030105',
      화면명: '신규번호 검색',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S101030106',
      화면명: '부가서비스 추가/삭제',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '	/pub/PopList',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S101040101',
      화면명: '동의',
      Depth1: '신규/변경 신청서 > 동의',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S101040104',
      화면명: '신청정보 확인 (신청서 확인)',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '2026-04-03',
      비고: '버튼추가',
    },
    {
      ID: 'S101040102',
      화면명: '판매자 서명',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - eformsign',
    },
    {
      ID: 'S101040103',
      화면명: '가입자(대리인) 서명',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '',
      상태: 'removed',
      완료일: '',
      최종수정일: '',
      비고: 'UI - eformsign',
    },
    {
      ID: 'S101050101',
      화면명: '신청완료',
      Depth1: '신규/변경 신청서 > 신청완료',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/S101050101',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S101050102',
      화면명: '신청서 열람 비밀번호 입력',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: '',
    },
    {
      ID: 'S101050103',
      화면명: '신청서 열람',
      Depth1: '',
      Depth2: '',
      Depth3: '',
      PATH: '/pub/PopList',
      상태: 'completed',
      완료일: '2026-03-27',
      최종수정일: '',
      비고: '',
    },
  ],
}
export default formNewChg
