devopsPath=devops/jenkins
mvnSetFile=settings-new.xml
mvnSecSetFile=settings-security.xml
mvnPomFile=pom-new.xml
utilPropsFile=remote-new.yml
instanceShell=ctrl.sh
releaseDir=/home/jenkins/data/release
credId=MSC-PRX-PRD
remoteId=jboss
remoteHost1=MSC-PRX1-PRD
remoteHost2=MSC-PRX2-PRD

isType=war
wasDocs=/jboss/applications
instDocs=/jboss/domains