devopsPath=devops/jenkins
utilPropsFile=remote-new.yml
releaseDir=/home/jenkins/data/release
tarFile=tar

distDocs=/apache/apache24/dist
webDocs=/apache/apache24/www
nasDocs=/nas/uploadfiles
linkPath=src/resources/upload
mpNasDocs=/mportal/default/resources/upload
mpLinkPath=src/resources/msp/upload