#### Common Profile

## Server - Servlet Container
server:
  port: 8080
  tomcat:
    connection-timeout: 2800
    keep-alive-timeout: -1
    max-keep-alive-requests: -1
    threads:
      max: 200
      min-spare: 200
  accept-count: 100
  shutdown: graceful
  forward-headers-strategy: framework



## Spring
spring:
  ## Security
  security:
    authorization:
      permit-all-urls:
        - /api/n/**
        - /actuator/prometheus
      token-ignore-urls:
        - /api/n/**
    jwt:
      secret-key: ${SECURITY_JWT_SECRET_KEY}
      issuer: kt-Mmobile-SmartForm

  ## Request Log
  request-log:
    exclude-url-patterns:
      - /favicon.ico
      - /actuator/**

  ## Servlet Multipart Handling
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  ## Binding
  binding:
    string-trim: true
    string-empty-as-null: false



## Logging
logging:
  pattern:
    correlation: "[%X{traceId}-%X{spanId}][%X{clientId}] "



## Actuator
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: health, prometheus
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.9, 0.95, 0.99
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:${OTEL_EXPORTER_OTLP_ENDPOINT:}}
  otlp:
    metrics:
      export:
        enabled: false



---
#### PRD Profile
spring:
  config.activate.on-profile: prd

## Response Handling
response-handling:
  exception:
    className: false
    message: true



---
#### STG Profile
spring:
  config.activate.on-profile: stg

## Response Handling
response-handling:
  exception:
    className: false
    message: true



---
#### DEV Profile
spring:
  config.activate.on-profile: dev

## Response Handling
response-handling:
  exception:
    className: false
    message: true



---
#### LOCAL Profile
spring:
  config.activate.on-profile: local

  ## Security
  security:
    jwt:
      secret-key: ENC(peB8Z1gpdde6RFV2gPM4xmq+AamVsosvePPhuvJDdCtJNR2YHfgM5BUoCDwY7ZJkwe19LgNam8tD9J8LOoh51+kbQkN7K/BxjcxCzJQvrGU=)

## Response Handling
response-handling:
  exception:
    className: false
    message: true

## Logging
logging:
  pattern:
    correlation: "[%X{clientId}] "

## Actuator
management:
  tracing:
    export:
      otlp:
        enabled: false
