devopsPath=devops/jenkins
mvnSetFile=settings-new.xml
mvnPomFile=pom-new.xml
mvnSecSetFile=settings-security.xml
utilPropsFile=remote-new.yml
instanceShell=ctrl.sh
releaseDir=/home/jenkins/data/release

isType=war
wasDocs=/deployments
instDocs=/home/jboss/domains