devopsPath=devops/jenkins
mvnSetFile=settings.xml
mvnSecSetFile=settings-security.xml
mvnPomFile=pom.xml
utilPropsFile=remote.yml
instanceShell=ctrl.sh
releaseDir=/data/release

isType=war
wasDocs=/deployments
instDocs=/home/jboss/domains