package com.ktmmobile.msf.domains.form.form.common.vo;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
public class McpRequestVo {

    long requestKey;
    String managerCode = "";
    String agentCode = "";
    String serviceType = "";
    String operType = "";
    String cstmrType = "";
    String resCode = "";
    String resMsg = "";
    String resNo = "";
    String clausePriCollectFlag = "";
    String clausePriOfferFlag = "";
    String clauseEssCollectFlag = "";
    String clausePriTrustFlag = "";
    String clausePriAdFlag = "";
    String clauseConfidenceFlag = "";
    String onlineAuthType = "";
    String onlineAuthInfo = "";
    String pstate = "";
    String requestStateCode = "";
    String openNo = "";
    String file01 = "";
    String file01Mask = "";
    String faxyn = "";
    String faxnum = "";
    String scanId = "";
    String onOffType = "";
    String rip = "";
    String openReqDate = "";
    String sysRdate = "";
    String reqWantNumber = "";
    String reqWantNumber2 = "";
    String reqWantNumber3 = "";
    String reqBuyType = "";
    String reqModelName = "";
    String reqModelColor = "";
    String reqPhoneSn = "";
    String reqUsimSn = "";
    String reqPayType = "";
    String reqAddition = "";
    String shopCd = "";
    String appFormYn = "";
    String reqInDay = "";
    String contractNum = "";
    String etcSpecial = "";
    String reqUsimName = "";
    String phonePayment = "";
    String reqAdditionPrice = "";
    String appFormXmlYn = "";
    String spcCode = "";
    String cntpntShopId = "";
    String shopUsmId = "";
    String memo = "";
    String recYn = "";
    String openMarketReferer = "";
    String soCd = "";
    String nwBlckAgrmYn = "";
    String appBlckAgrmYn = "";
    String appCd = "";
    String soTrnsAgrmYn = "";
    String clauseJehuFlag = "";
    String shopNm = "";
    String prodId = "";
    String cretId = "";
    String bannerCd = "";
    String sntyColorCd = "";
    String sntyCapacCd = "";
    String prodType = "";
    String clauseRentalModelCp = "";
    String clauseRentalModelCpPr = "";
    String clauseRentalService = "";
    String clauseMpps35Flag = "";
    String clauseFinanceFlag = "";
    String rvisnId = "";
    String rvisnDttm = "";
    String promotionCd = "";
    String realShopNm = "";
    String usimKindsCd = "";
    String insrCd = "";
    String clauseInsuranceFlag = "";
    String prodNm = "";
    String insrProdCd = "";
    String clauseInsrProdFlag = "";
    String insrAuthInfo = "";
    String clause5gCoverageFlag = "";
    String ktmReferer = "";
    String eid = "";
    String imei1 = "";
    String imei2 = "";
    String uploadPhoneSrlNo = "";
    String esimPhoneId = "";
    String prntsContractNo = "";
    String countryCode = "";
    String rwdProdCd = "";
    String clauseRwdFlag = "";
    String rwdAuthInfo = "";
    String personalInfoCollectAgree = "";
    String othersTrnsAgree = "";
    String disPrmtId = "";
    String hubOrderSeq = "";
    String clauseSensiCollectFlag = "";
    String clauseSensiOfferFlag = "";
    String clausePartnerOfferFlag = "";
    String jehuProdType = "";
    String openMarketId = "";
    String jehuPartnerType = "";
    String othersTrnsKtAgree = "";
    String othersAdReceiveAgree = "";
    String evntCdPrmt = "";
    String fathTrgYn = "";
    String clauseFathFlag = "";
    String fathTransacId = "";
    String fathCmpltNtfyDt = "";
    String cpntId = "";
    String combineSoloType = "";
    String combineSoloFlag = "";
    String indvLocaPrvAgree = "";
    String ktCounselAgree = "";
    String pstateReasonCode = "";
    String pstateReasonEtc = "";

    @Override
    public String toString() {
        return "McpRequestVo{" +
                "requestKey=" + requestKey +
                ", managerCode='" + managerCode + '\'' +
                ", agentCode='" + agentCode + '\'' +
                ", serviceType='" + serviceType + '\'' +
                ", operType='" + operType + '\'' +
                ", cstmrType='" + cstmrType + '\'' +
                ", resCode='" + resCode + '\'' +
                ", resMsg='" + resMsg + '\'' +
                ", resNo='" + resNo + '\'' +
                ", clausePriCollectFlag='" + clausePriCollectFlag + '\'' +
                ", clausePriOfferFlag='" + clausePriOfferFlag + '\'' +
                ", clauseEssCollectFlag='" + clauseEssCollectFlag + '\'' +
                ", clausePriTrustFlag='" + clausePriTrustFlag + '\'' +
                ", clausePriAdFlag='" + clausePriAdFlag + '\'' +
                ", clauseConfidenceFlag='" + clauseConfidenceFlag + '\'' +
                ", onlineAuthType='" + onlineAuthType + '\'' +
                ", onlineAuthInfo='" + onlineAuthInfo + '\'' +
                ", pstate='" + pstate + '\'' +
                ", requestStateCode='" + requestStateCode + '\'' +
                ", openNo='" + openNo + '\'' +
                ", file01='" + file01 + '\'' +
                ", file01Mask='" + file01Mask + '\'' +
                ", faxyn='" + faxyn + '\'' +
                ", faxnum='" + faxnum + '\'' +
                ", scanId='" + scanId + '\'' +
                ", onOffType='" + onOffType + '\'' +
                ", rip='" + rip + '\'' +
                ", openReqDate='" + openReqDate + '\'' +
                ", sysRdate='" + sysRdate + '\'' +
                ", reqWantNumber='" + reqWantNumber + '\'' +
                ", reqWantNumber2='" + reqWantNumber2 + '\'' +
                ", reqWantNumber3='" + reqWantNumber3 + '\'' +
                ", reqBuyType='" + reqBuyType + '\'' +
                ", reqModelName='" + reqModelName + '\'' +
                ", reqModelColor='" + reqModelColor + '\'' +
                ", reqPhoneSn='" + reqPhoneSn + '\'' +
                ", reqUsimSn='" + reqUsimSn + '\'' +
                ", reqPayType='" + reqPayType + '\'' +
                ", reqAddition='" + reqAddition + '\'' +
                ", shopCd='" + shopCd + '\'' +
                ", appFormYn='" + appFormYn + '\'' +
                ", reqInDay='" + reqInDay + '\'' +
                ", contractNum='" + contractNum + '\'' +
                ", etcSpecial='" + etcSpecial + '\'' +
                ", reqUsimName='" + reqUsimName + '\'' +
                ", phonePayment='" + phonePayment + '\'' +
                ", reqAdditionPrice='" + reqAdditionPrice + '\'' +
                ", appFormXmlYn='" + appFormXmlYn + '\'' +
                ", spcCode='" + spcCode + '\'' +
                ", cntpntShopId='" + cntpntShopId + '\'' +
                ", shopUsmId='" + shopUsmId + '\'' +
                ", memo='" + memo + '\'' +
                ", recYn='" + recYn + '\'' +
                ", openMarketReferer='" + openMarketReferer + '\'' +
                ", soCd='" + soCd + '\'' +
                ", nwBlckAgrmYn='" + nwBlckAgrmYn + '\'' +
                ", appBlckAgrmYn='" + appBlckAgrmYn + '\'' +
                ", appCd='" + appCd + '\'' +
                ", soTrnsAgrmYn='" + soTrnsAgrmYn + '\'' +
                ", clauseJehuFlag='" + clauseJehuFlag + '\'' +
                ", shopNm='" + shopNm + '\'' +
                ", prodId='" + prodId + '\'' +
                ", cretId='" + cretId + '\'' +
                ", bannerCd='" + bannerCd + '\'' +
                ", sntyColorCd='" + sntyColorCd + '\'' +
                ", sntyCapacCd='" + sntyCapacCd + '\'' +
                ", prodType='" + prodType + '\'' +
                ", clauseRentalModelCp='" + clauseRentalModelCp + '\'' +
                ", clauseRentalModelCpPr='" + clauseRentalModelCpPr + '\'' +
                ", clauseRentalService='" + clauseRentalService + '\'' +
                ", clauseMpps35Flag='" + clauseMpps35Flag + '\'' +
                ", clauseFinanceFlag='" + clauseFinanceFlag + '\'' +
                ", rvisnId='" + rvisnId + '\'' +
                ", rvisnDttm='" + rvisnDttm + '\'' +
                ", promotionCd='" + promotionCd + '\'' +
                ", realShopNm='" + realShopNm + '\'' +
                ", usimKindsCd='" + usimKindsCd + '\'' +
                ", insrCd='" + insrCd + '\'' +
                ", clauseInsuranceFlag='" + clauseInsuranceFlag + '\'' +
                ", prodNm='" + prodNm + '\'' +
                ", insrProdCd='" + insrProdCd + '\'' +
                ", clauseInsrProdFlag='" + clauseInsrProdFlag + '\'' +
                ", insrAuthInfo='" + insrAuthInfo + '\'' +
                ", clause5gCoverageFlag='" + clause5gCoverageFlag + '\'' +
                ", ktmReferer='" + ktmReferer + '\'' +
                ", eid='" + eid + '\'' +
                ", imei1='" + imei1 + '\'' +
                ", imei2='" + imei2 + '\'' +
                ", uploadPhoneSrlNo='" + uploadPhoneSrlNo + '\'' +
                ", esimPhoneId='" + esimPhoneId + '\'' +
                ", prntsContractNo='" + prntsContractNo + '\'' +
                ", countryCode='" + countryCode + '\'' +
                ", rwdProdCd='" + rwdProdCd + '\'' +
                ", clauseRwdFlag='" + clauseRwdFlag + '\'' +
                ", rwdAuthInfo='" + rwdAuthInfo + '\'' +
                ", personalInfoCollectAgree='" + personalInfoCollectAgree + '\'' +
                ", othersTrnsAgree='" + othersTrnsAgree + '\'' +
                ", disPrmtId='" + disPrmtId + '\'' +
                ", hubOrderSeq='" + hubOrderSeq + '\'' +
                ", clauseSensiCollectFlag='" + clauseSensiCollectFlag + '\'' +
                ", clauseSensiOfferFlag='" + clauseSensiOfferFlag + '\'' +
                ", clausePartnerOfferFlag='" + clausePartnerOfferFlag + '\'' +
                ", jehuProdType='" + jehuProdType + '\'' +
                ", openMarketId='" + openMarketId + '\'' +
                ", jehuPartnerType='" + jehuPartnerType + '\'' +
                ", othersTrnsKtAgree='" + othersTrnsKtAgree + '\'' +
                ", othersAdReceiveAgree='" + othersAdReceiveAgree + '\'' +
                ", evntCdPrmt='" + evntCdPrmt + '\'' +
                ", fathTrgYn='" + fathTrgYn + '\'' +
                ", clauseFathFlag='" + clauseFathFlag + '\'' +
                ", fathTransacId='" + fathTransacId + '\'' +
                ", fathCmpltNtfyDt='" + fathCmpltNtfyDt + '\'' +
                ", cpntId='" + cpntId + '\'' +
                ", combineSoloType='" + combineSoloType + '\'' +
                ", combineSoloFlag='" + combineSoloFlag + '\'' +
                ", indvLocaPrvAgree='" + indvLocaPrvAgree + '\'' +
                ", ktCounselAgree='" + ktCounselAgree + '\'' +
                ", pstateReasonCode='" + pstateReasonCode + '\'' +
                ", pstateReasonEtc='" + pstateReasonEtc + '\'' +
                '}';
    }
}
