
SERVER_NAME=REAL

server.port = 9080

#APP PUSH sendOne
push.interface.server=http://10.20.28.87:8251/push/sendPushToFCM.do

#APP PUSH sendAll - Android
fcm.multi.android.server = http://10.20.28.87:8251/push/sendPushAllAndroid.do

#APP PUSH sendAll - IOS
fcm.multi.ios.server = http://10.20.28.87:8251/push/sendPushAllIos.do

inf.url = http://10.20.28.87:7006

# DB - oracle
spring.datasource.hikari.bootoradb.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.bootoradb.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=ON)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=10.21.28.202)(PORT=1522))(ADDRESS=(PROTOCOL=TCP)(HOST=10.21.28.204)(PORT=1522)))(CONNECT_DATA=(SERVICE_NAME=MCP)(GLOBAL_NAME=MCP)(failover_mode=(type=session)(method=basic))))
spring.datasource.hikari.bootoradb.username=MCP_WAS_CP
spring.datasource.hikari.bootoradb.password=ktmm0601!!
spring.datasource.hikari.bootoradb.maxActive=50
spring.datasource.hikari.bootoradb.defaultAutoCommit=false
spring.datasource.hikari.bootoradb.validationQuery=select 1 from dual
spring.datasource.hikari.bootoradb.testWhileIde=true
spring.datasource.hikari.bootoradb.timeBetweenEvictionRunsMillis=7200000

spring.task.scheduling.pool.size=100

# DB - event
spring.datasource.hikari.booteventdb.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.booteventdb.jdbc-url=jdbc:postgresql://10.221.18.5:7031/mcpevent
spring.datasource.hikari.booteventdb.username=mcpeventwas
spring.datasource.hikari.booteventdb.password=ktmm0601!!
spring.datasource.hikari.booteventdb.maxActive=50
spring.datasource.hikari.booteventdb.defaultAutoCommit=false
spring.datasource.hikari.booteventdb.validationQuery=select 1 from dual
spring.datasource.hikari.booteventdb.testWhileIde=true
spring.datasource.hikari.booteventdb.timeBetweenEvictionRunsMillis=7200000

# ELASTIC SEARCH
elastic.url=10.21.28.225

#API server
api.interface.server = http://10.21.28.224:28080

#SCAN url
scan.url = 10.21.28.78:8080/appform/sendScanAjax.do?requestKey=


#rate url
rate.url = 10.21.28.78:8080/batch/resChangeAddPrdAjax.do

# MCP-API-EXT
ext.url = http://10.20.28.87:8251

mcp.was.server=10.21.28.78:8080,10.21.28.78:8180,10.21.28.107:8080,10.21.28.107:8180

juice.url=http://10.20.28.87:7006/mPlatform/serviceCall.do
juice.json.url=http://10.20.28.87:7006/mPlatform/serviceCallJson.do
osst.simple.open.url=http://10.20.28.87:7006/mPlatform/simpleOpenServiceCall.do
osst.url=http://10.20.28.87:7006/mPlatform/osstServiceCall.do

sms.callcenter=18995000

admin.url = http://10.21.28.98:8080
admin.fileupload.path = /nas/uploadfiles/prd
temp.fileupload.path = /home/jboss/temp/uploadfiles

# MCP-ACEN-REQ (ext)
#acen.req.url = http://10.20.28.87:8251
# MCP-ACEN-REQ (req)
acen.req.url = http://10.20.28.87:8282

fath.url= https://www.ktmmobile.com/fath/fathAuth.do