# [DataBase Environment ] - DataBase Postgres Plus Advanced Server
# ----------------------------------------------------------------
mvno.oracle.jdbc.driver=oracle.jdbc.driver.OracleDriver
mvno.oracle.jdbc.maxActive=50
mvno.oracle.jdbc.initialSize=5
# --- \uc6b4\uc601\uacc4\uc815 ---
mvno.oracle.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=ON)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=10.21.28.203)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=10.21.28.205)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=MSP)(GLOBAL_NAME=MSP)(failover_mode=(type=session)(method=basic))))
mvno.oracle.user=MSP_WAS
mvno.oracle.password=ktmm0601!!

# method - (DB Update\ub97c direct\ub85c \uc218\ud589\ud560 \uc9c0, Spool\uc744 \ud1b5\ud574 \uc218\ud589\ud560 \uc9c0 \uc124\uc815)
# interval - (DB Update\uac00 Spool \uc720\ud615\uc77c \uacbd\uc6b0 \uc8fc\uae30\uc801\uc73c\ub85c \uac80\uc0ac\ud558\ub294 \uc2dc\uac04 \ub2e8\uc704(\ucd08)
mvno.oracle.update.method=spool
mvno.oracle.update.interval=10

jdbc.jndi.name=java:/jdbc/mspDS
