devopsPath=devops/jenkins
mvnSetFile=settings.xml
mvnSecSetFile=settings-security.xml
mvnPomFile=pom.xml
utilPropsFile=remote.yml
instanceShell=ctrl.sh
releaseDir=/data/release
credId=MSC-PRX-PRD
remoteId=jboss
remoteHost1=MSC-PRX1-PRD
remoteHost2=MSC-PRX2-PRD

isType=war
wasDocs=/jboss/applications
instDocs=/jboss/domains