# [Admin Environment ] - Runtime rule
# runtype = 0(\uac1c\ubc1c\uc11c\ubc84) 1(\uc6b4\uc601\uc11c\ubc84)
# ################################################################
mvno.admin.policyfile= 
mvno.admin.runtype=0
mvno.admin.sessiontimeout=3600
mvno.admin.intervallog=10
mvno.admin.intervalstat=10

# [Strategy Environment ] - Runtime rule
# ################################################################
# Parameter: loglevel - (0: DEBUG \ub85c\uae45 turn off  16\uc9c4\uc218: level)
# Parameter: sessiontimeout - (\uc138\uc158Timeout\uc2dc\uac04 \ud639\uc740 \uc778\uc99d\ubc88\ud638 \uc785\ub825 \uc2dc\uac04 \uc81c\ud55c(\ub2e8\uc704 \ucd08), 0\uc740 \uc81c\ud55c \uc5c6\uc74c)
# Parameter: disablemenu - (\uc6f9\ud398\uc774\uc9c0\ub0b4\uc5d0\uc11c \uc6b0\uce21\ud074\ub9ad-\uba54\ub274 1-Disable, 0-Allow)
mvno.policy.loglevel=FF
mvno.policy.sessiontimeout=180
mvno.policy.disablemenu=0

mvno.validation.mobileweb=(.*android)|(.*iphone)