-- SVC_TGT_CD EXPNSN_STR_VAL1/VAL2 의미 정정
-- EXPNSN_STR_VAL1 = 동시변경 가능 여부 (Y=가능, N=불가)
-- EXPNSN_STR_VAL2 = 별도신청서 리포트 이미지 처리 여부

-- 1. GROUP_BAS: 컬럼 의미 기록
UPDATE MSF_CD_GROUP_BAS
SET EXPNSN_STR_VAL1 = 'CONCURRENT_AVAIL_YN',
    EXPNSN_STR_VAL2 = 'IMAGING_YN'
WHERE CD_GROUP_ID = 'SVC_TGT_CD';

-- 2. DTL: EXPNSN_STR_VAL1 값 반전
--    기존: Y=동시처리차단(불가) / N=차단없음(가능)
--    변경: Y=동시변경가능     / N=동시변경불가
UPDATE MSF_CD_DTL
SET EXPNSN_STR_VAL1 = CASE EXPNSN_STR_VAL1 WHEN 'Y' THEN 'N' WHEN 'N' THEN 'Y' ELSE EXPNSN_STR_VAL1 END
WHERE CD_GROUP_ID = 'SVC_TGT_CD';

-- 결과 확인: RATE_CHANGE/LOST_RESTORE/NUM_CHANGE = N, 나머지 = Y
SELECT DTL_CD, DTL_CD_NM, EXPNSN_STR_VAL1 AS concurrent_avail_yn, EXPNSN_STR_VAL2 AS imaging_yn
FROM MSF_CD_DTL WHERE CD_GROUP_ID='SVC_TGT_CD' ORDER BY SORT_ODRG;
