config:
  credentials_id: MSC-PRX-PRD
#  retry_with_prompt: true
#  retry_and_return: true
#  retry_count: 3

remote_groups:
  r_group_1:
    - name: jboss
      host: MSC-PRX1-PRD
    - name: jboss
      host: MSC-PRX2-PRD

command_groups:
  c_group_1:
    - puts:
        - from: '/home/jenkins/data/release/prd/msc-prx/msc-prx.war'
          into: '/jboss/applications/msc-prx/was/'
          override: true
        - from: '/home/jenkins/data/release/prd/msc-prx/ctrl.sh'
          into: '/jboss/domains/'
          override: true
    - commands:
        - 'chmod 755 /jboss/applications/msc-prx/was/msc-prx.war'
        - 'ls -lrt /jboss/applications/msc-prx/was/msc-prx.war'
        - 'chmod 755 /jboss/domains/ctrl.sh'
        - 'ls -lrt /jboss/domains/ctrl.sh'

steps:
  deploy:
    - remote_groups:
        - r_group_1
      command_groups:
        - c_group_1