# M PLATFORM

#PRX PRD
juice.url=http://10.20.28.87:7006/mPlatform/serviceCall.do
osst.url=http://10.20.28.87:7006/mPlatform/osstServiceCall.do
osst.simple.open.url=http://10.20.28.87:7006/mPlatform/simpleOpenServiceCall.do
