
SERVER_NAME=DEV

server.port = 9080

#APP PUSH sendOne
push.interface.server=http://10.20.28.38:8251/push/sendPushToFCM.do

#APP PUSH sendAll - Android
fcm.multi.android.server = http://10.20.28.38:8251/push/sendPushAllAndroid.do

#APP PUSH sendAll - IOS
fcm.multi.ios.server = http://10.20.28.38:8251/push/sendPushAllIos.do

inf.url = http://10.20.28.38:7006

# DB - oracle
spring.datasource.hikari.bootoradb.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.bootoradb.jdbc-url=jdbc:oracle:thin:@10.220.71.231:1521:MCPDEVRN
spring.datasource.hikari.bootoradb.username=MCP_WAS_CP
spring.datasource.hikari.bootoradb.password=ktmm0601!!

# DB - event
spring.datasource.hikari.booteventdb.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.booteventdb.jdbc-url=jdbc:postgresql://10.221.18.5:7011/mcpevent
spring.datasource.hikari.booteventdb.username=mcpeventwas
spring.datasource.hikari.booteventdb.password=ktmm0601!!

# ELASTIC SEARCH
elastic.url=10.21.28.100

#API server
api.interface.server = http://10.21.28.57:28080
#api.interface.server = http://localhost:9380


#SCAN url
scan.url = 10.21.28.54:8080/appform/sendScanAjax.do?requestKey=

#rate url
rate.url = 10.21.28.54:8080/batch/resChangeAddPrdAjax.do

# MCP-API-EXT
ext.url = http://10.20.28.38:8251

#mcp.was.server=10.21.28.54:8080,10.21.28.33:8080,10.21.28.54:8080,10.21.28.33:8080
mcp.was.server=local.portal.ktmmobile.com,local.portal.ktmmobile.com,local.portal.ktmmobile.com,local.portal.ktmmobile.com

juice.url=http://10.20.28.38:7006/mPlatform/serviceCall.do
juice.json.url=http://10.20.28.38:7006/mPlatform/serviceCallJson.do
osst.simple.open.url=http://10.20.28.38:7006/mPlatform/simpleOpenServiceCall.do
osst.url=http://10.20.28.38:7006/mPlatform/osstServiceCall.do

sms.callcenter=18995000

admin.url = http://10.21.28.49:8080
admin.fileupload.path = /nas/uploadfiles/dev
temp.fileupload.path = /home/jboss/temp/uploadfiles

# MCP-ACEN-REQ (ext)
#acen.req.url = http://10.20.28.38:8251
# MCP-ACEN-REQ (req)
acen.req.url = http://10.20.28.38:8282

fath.url= https://dmcpstg.ktmmobile.com/fath/fathAuth.do