config:
  credentials_id: MCP-WAS-widget-PRD
#  retry_with_prompt: true
#  retry_and_return: true
#  retry_count: 3

remote_groups:
  r_group_1:
    - name: jboss
      host: MCP-WAS1-widget-PRD
    - name: jboss
      host: MCP-WAS2-widget-PRD

command_groups:
  c_group_1:
    - puts:
        - from: '/data/release/prd/mcp-widget/mcp-widget.war'
          into: '/jboss/applications/mcp-widget/was/'
          override: true
        - from: '/data/release/prd/mcp-widget/ctrl.sh'
          into: '/jboss/domains/'
          override: true
    - commands:
        - 'chmod 755 /jboss/applications/mcp-widget/was/mcp-widget.war'
        - 'ls -lrt /jboss/applications/mcp-widget/was/mcp-widget.war'
        - 'chmod 755 /jboss/domains/ctrl.sh'
        - 'ls -lrt /jboss/domains/ctrl.sh'
        - 'cd /jboss/domains; sh ctrl.sh'

steps:
  deploy:
    - remote_groups:
        - r_group_1
      command_groups:
        - c_group_1