#### Spring
spring:
  #### DataSource
  datasource:

  #### Spring Data
  data:
    #### Redis
    redis:
      host:
      port: 6379



#### Logging
logging:
  on-ready:
    jdbc:
      sqltiming: debug
  level:
    com.ktmmobile.msf: debug
    jdbc:
      sqlonly: off
      sqltiming: off
      resultsettable: debug
      audit: off
      resultset: off
      connection: off
