## Common
common:
  public-url:
    form-service:  ## 환경별 설정
    admin-service: ## 환경별 설정



## Spring
spring:
  ## Basic
  base-package: com.ktmmobile.msf
  lifecycle.timeout-per-shutdown-phase: 1m

  ## DataSource
  datasource:
    groups:
      ## 스마트서식지
      smartform:
        type: ROUTING
        writer:
          hikari:
            maximum-pool-size: 20
        reader:
          read-only: true
          url: ${spring.datasource.groups.smartform.writer.url}
          username: ${spring.datasource.groups.smartform.writer.username}
          password: ${spring.datasource.groups.smartform.writer.password}
          hikari:
            maximum-pool-size: 30

      ## M전산
      msp:
        type: STANDALONE
        standalone:
          read-only: true
          hikari:
            maximum-pool-size: 20
            max-lifetime: 300000
            data-source-properties:
              "oracle.jdbc.timezoneAsRegion": false

    hikari:
      connection-timeout: 2700
      validation-timeout: 1000
      keepalive-time: 30000
      max-lifetime: 60000
      leak-detection-threshold: 59000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  ## Spring Data
  data:
    ## Redis
    redis:
      timeout: 500ms
      connect-timeout: 200ms
      lettuce:
        shutdown-timeout: 500ms
        cluster:
          refresh:
            period: 60s
            dynamic-refresh-sources: true

  ## TaskExecutor
  task:
    ## @Scheduled
    scheduling:
      pool.size: 5
      thread-name-prefix: scheduling-
      shutdown:
        await-termination: true
        await-termination-period: 1m

    ## @Async
    execution:
      pool:
        core-size: 20
        max-size: 50
        queue-capacity: 100
      thread-name-prefix: async-
      shutdown:
        await-termination: true
        await-termination-period: 1m



## 메시지 발송
message-sender:
  kakao: ## 카카오톡 알림톡
    sender-key:  ## 각 환경별 설정



## Jasypt
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}



## Scheduling
scheduling:
  enabled: true



## Startup Load
startup:
  load:
    exclude: []



## Logging
http-log:
  default-rules:
    ## HTTP 로그 헤더 기본 룰
    ## 헤더명 뒤에 [size] 또는 [start:end] 지정 가능
    header-names:
      include:
        - Content-Type
        - Authorization[10]
        - X-Service-Api-Key[10]
      exclude:
        - X-Content-Type-Options
      #additional-include: { }
      #additional-exclude: { }

    ## HTTP 로그 바디(JSON, form-urlencoded, form-data) 마스킹 기본 룰
    body-masked-fields:
      include:
        - authorization
        - password
        - authNumber
        - secret
        - token
        - passwd
        - apiKey
      exclude:
        - tokenType
      #additional-include: { }
      #additional-exclude: { }

    ## HTTP 로그 바디(JSON, form-urlencoded, form-data) 축약 기본 룰
    ## 필드명 뒤에 [size] 또는 [start:end] 지정 가능
    body-truncated-fields:
      default-truncated-size: 50
      include:
        - accessToken[10]
        - loginSessionId[8:]
        - content
        - image
        - file
      exclude: []
      #additional-include: { }
      #additional-exclude: { }



logging:
  pattern:
    correlation: "[%X{traceId}-%X{spanId}][%X{clientId}] "
  level:
    com.ktmmobile.msf: info
