spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.data.redis.autoconfigure.DataRedisAutoConfiguration
      - org.springframework.boot.data.redis.autoconfigure.DataRedisRepositoriesAutoConfiguration

  ## DataSource
  datasource:
    groups:
      ## 스마트서식지
      smartform:
        writer:
          url: jdbc:log4jdbc:postgresql://211.184.227.24:45432/msf_core?currentSchema=smartform
          username: ENC(thA33IuMOECiHqyms2uS27np3TgktbegPCUdj3EjldM9A/tbNFHJ/JBpYzML2hZw)
          password: ENC(hzVv7kRZCnauKm5MKtE3u4VJ18ZChTgxfxwfTD+xWxbzIeQcgLaXHZoXyRYV4FqaAlti+hnUPvmSyRuvWvFIdw==)
          hikari:
            maximum-pool-size: 6
        reader:
          url: ${spring.datasource.groups.smartform.writer.url}
          username: ${spring.datasource.groups.smartform.writer.username}
          password: ${spring.datasource.groups.smartform.writer.password}
          hikari:
            maximum-pool-size: 6

      ## M전산
      msp:
        standalone:
          url: jdbc:log4jdbc:oracle:thin:@10.220.71.231:2521:MSPDEV
          username: ENC(wEFQiRtDlU3uKddGAg/7dB94KeYcusJz8jhYLqaa+NMNeiIsU6uaCfBw39RWrPtW)
          password: ENC(LPbBY5knhFrbtRuJOQRNap5ms+S+uE7id2NhBTspqOaqIVbATF+k1LbdH2wYOtni)
          hikari:
            maximum-pool-size: 6
            idle-timeout: 290000
            data-source-properties:
              "oracle.jdbc.timezoneAsRegion": false

    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 3
      idle-timeout: 59000
      keepalive-time: 20000

  ## Spring Data
  data:
    ## Redis
    redis:
      enabled: false
      host:
      port: 6379
      password: ENC(...)

api:
  interface:
    server: http://localhost:9380
    use-mcp: false   # true: mcp-api 호출 (연결실패 시 MSP fallback), false: MSP 직접 조회

management:
  health:
    redis:
      enabled: false



## Logging
logging:
  pattern:
    correlation: "[%X{clientId}] "
  level:
    com.ktmmobile.msf: debug
    jdbc:
      sqlonly: off
      sqltiming: off
      resultsettable: debug
      audit: off
      resultset: off
      connection: off



## Jasypt
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
