## Spring
spring:
  ## Basic
  base-package: com.ktmmobile.msf
  lifecycle.timeout-per-shutdown-phase: 1m

  ## DataSource
  datasource:
    groups:
      ## 스마트서식지
      smartform:
        type: ROUTING
        writer:
          url: ${SMARTFORM_WRITER_DB_URL}
          username: ${SMARTFORM_WRITER_DB_USERNAME}
          password: ${SMARTFORM_WRITER_DB_PASSWORD}
          hikari:
            maximum-pool-size: 20
        reader:
          url: ${SMARTFORM_READER_DB_URL}
          username: ${SMARTFORM_READER_DB_USERNAME}
          password: ${SMARTFORM_READER_DB_PASSWORD}
          read-only: true
          hikari:
            maximum-pool-size: 30

      ## M전산
      msp:
        type: STANDALONE
        standalone:
          url: ${MSP_DB_URL}
          username: ${MSP_DB_USERNAME}
          password: ${MSP_DB_PASSWORD}
          read-only: true
          hikari:
            maximum-pool-size: 20
            max-lifetime: 300000

      ## MCP (레거시 M포탈)
      mcp:
        type: STANDALONE
        standalone:
          url: ${MCP_DB_URL}
          username: ${MCP_DB_USERNAME}
          password: ${MCP_DB_PASSWORD}
          read-only: true
          hikari:
            maximum-pool-size: 20
            max-lifetime: 300000

    hikari:
      connection-timeout: 2700
      validation-timeout: 1000
      keepalive-time: 30000
      max-lifetime: 60000
      leak-detection-threshold: 59000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  ## Spring Data
  data:
    ## Redis
    redis:
      host:
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: 500ms
      connect-timeout: 200ms
      lettuce:
        shutdown-timeout: 500ms
        cluster:
          refresh:
            period: 60s
            dynamic-refresh-sources: true
            adaptive: false

  ## TaskExecutor
  task:
    ## @Scheduled
    scheduling:
      pool.size: 5
      thread-name-prefix: scheduling-
      shutdown:
        await-termination: true
        await-termination-period: 1m

    ## @Async
    execution:
      pool:
        core-size: 20
        max-size: 50
        queue-capacity: 100
      thread-name-prefix: async-
      shutdown:
        await-termination: true
        await-termination-period: 1m



## Scheduling
scheduling:
  enabled: true



## Startup Load
startup:
  load:
    exclude: []



## Logging
logging:
  pattern:
    correlation: "[%X{traceId}-%X{spanId}][%X{clientId}] "
  level:
    com.ktmmobile.msf: info



---
#### PRD Profile
spring:
  config.activate.on-profile: prd



---
#### STG Profile
spring:
  config.activate.on-profile: stg



---
#### DEV Profile
spring:
  config.activate.on-profile: dev

logging:
  on-ready:
    jdbc:
      sqltiming: debug
  level:
    com.ktmmobile.msf: debug
    jdbc:
      sqlonly: off
      sqltiming: off
      resultsettable: debug
      audit: off
      resultset: off
      connection: off



---
#### LOCAL Profile
spring:
  config.activate.on-profile: local

## 별도 파일에 프로퍼티 정의: application-common-local.yaml
