#### Spring
spring:
  #### DataSource
  datasource:

  #### Spring Data
  data:
    #### Redis
    redis:
      host:
      port: 6379



#### External Service
external-service:



#### Logging
logging:
  level:
