## Common
common:
  public-url:
    form-service: http://localhost:7080
    admin-service: http://localhost:7180



spring:
  ## DataSource
  datasource:
    groups:
      ## 스마트서식지
      smartform:
        writer:
          url: jdbc:log4jdbc:postgresql://211.184.227.24:45432/msf_core?currentSchema=smartform
          username: ENC(thA33IuMOECiHqyms2uS27np3TgktbegPCUdj3EjldM9A/tbNFHJ/JBpYzML2hZw)
          password: ENC(hzVv7kRZCnauKm5MKtE3u4VJ18ZChTgxfxwfTD+xWxbzIeQcgLaXHZoXyRYV4FqaAlti+hnUPvmSyRuvWvFIdw==)
          hikari:
            maximum-pool-size: 6
        reader:
          hikari:
            maximum-pool-size: 6

      ## M전산
      msp:
        standalone:
          url: jdbc:log4jdbc:oracle:thin:@10.220.71.231:2521:MSPDEV
          username: ENC(wEFQiRtDlU3uKddGAg/7dB94KeYcusJz8jhYLqaa+NMNeiIsU6uaCfBw39RWrPtW)
          password: ENC(LPbBY5knhFrbtRuJOQRNap5ms+S+uE7id2NhBTspqOaqIVbATF+k1LbdH2wYOtni)
          hikari:
            maximum-pool-size: 6
            idle-timeout: 290000
            data-source-properties:
              "oracle.jdbc.timezoneAsRegion": false

    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 3
      idle-timeout: 59000


  ## Spring Data
  data:
    ## Redis
    redis:
      enabled: true
      host: 211.184.184.30
      port: 46579
      password: ENC(r+Nby5IIIBQWUocgfadxFQQ1sGJCruM/FTqI3me4dw+XYkev0d+8/3Mfu8oqmjMaqrAHcxH+TXDurF9G8tF/GwH7bs/ES4joQFzDMnGUc1A=)
      timeout: 10s
      connect-timeout: 1s



## 메시지 발송
message-sender:
  kakao:
    sender-key: ENC(1vg4gHtg3jDyq1G7eqyZDmvZlT5m8Ocbzr/NjSCEOyVzPh+CruLOOP/QHYVaGT34/GxLXFFMqPEW6/LA2Ql0whQJ/1PGaA/E7kKn2QvqIqk=)



## Scheduling
scheduling:
  enabled: false



## Actuator
management:
  health:
    redis:
      enabled: false



api:
  interface:
    server: http://localhost:9380
    use-mcp: false   # true: mcp-api 호출 (연결실패 시 MSP fallback), false: MSP 직접 조회



## Logging
logging:
  include-application-name: false
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    correlation: "[%X{clientId}] "
  level:
    com.ktmmobile.msf: debug
    jdbc:
      sqlonly: off
      sqltiming: off
      resultsettable: debug
      audit: off
      resultset: off
      connection: off
