config:
  credentials_id: MSC-API-PRD
#  retry_with_prompt: true
#  retry_and_return: true
#  retry_count: 3

remote_groups:
  r_group_1:
    - name: jboss
      host: MSC-API1-PRD
    - name: jboss
      host: MSC-API2-PRD

command_groups:
  c_group_1:
    - puts:
        - from: '/data/release/prd/mcp-api/mcp-api.war'
          into: '/jboss/applications/mcp-api/was/'
          override: true
        - from: '/data/release/prd/mcp-api/ctrl.sh'
          into: '/jboss/domains/'
          override: true
    - commands:
        - 'chmod 755 /jboss/applications/mcp-api/was/mcp-api.war'
        - 'ls -lrt /jboss/applications/mcp-api/was/mcp-api.war'
        - 'chmod 755 /jboss/domains/ctrl.sh'
        - 'ls -lrt /jboss/domains/ctrl.sh'
        - 'cd /jboss/domains; sh ctrl.sh'

steps:
  deploy:
    - remote_groups:
        - r_group_1
      command_groups:
        - c_group_1