devopsPath=devops/jenkins
mvnSetFile=settings.xml
mvnSecSetFile=settings-security.xml
mvnPomFile=pom_deploy.new.xml
utilPropsFile0=remote-all.yml
utilPropsFile1=remote-was.yml
utilPropsFile2=remote-web.yml
utilPropsFile3=remote.yml
releaseDir=/home/jenkins/data/release