## Common Profile

app:
  config:
    comb-svc-no: "01027435432" # Y44 회선번호
    mst-svc-cont-id: "587838774" # Y44 결합회선번호

---
## PRD Profile
spring:
  config.activate.on-profile: prd



---
## STG Profile
spring:
  config.activate.on-profile: stg



---
## DEV Profile
spring:
  config.activate.on-profile: dev



---
## LOCAL Profile
spring:
  config.activate.on-profile: local
