## 외부 서비스
external-service:
  services:
    m-platform:
      base-url: https://m-platform-dev  # TODO: 수정
    msp-prx:
      base-url: https://msp-prx-dev  # TODO: 수정
    msp-api:
      base-url: https://msp-api-dev  # TODO: 수정
    msp-ext-api:
      base-url: https://msp-ext-dev  # TODO: 수정
