#### Common Profile
spring:
  http:
    ## 공통 설정
    clients:
      connect-timeout: 2s
      read-timeout: 5s

    ## 연동 대상 서비스:
    ## :domains:external-client 모듈 프로퍼티에 작성



## HTTP Client
http-client:
  proxy:
    enabled: false
    groups: []

  recording:
    enabled: true
    response-body-truncated-size: 1000  # Content-Type=text/*일 때 적용; 0으로 설정하면 축약하지 않음

    ## 바디(JSON, form-urlencoded, form-data) 필드 축약 공통 룰 확장
    body-truncated-fields:
      additional-include:
        http-client:
          - html
          - message[100]
