## 외부 서비스
external-service:
  services:
    m-platform:
      base-url: https://m-platform-prd  # TODO: 수정
    msp-prx:
      base-url: https://msp-prx-prd  # TODO: 수정
    msp-api:
      base-url: https://msp-api-prd  # TODO: 수정
    msp-ext-api:
      base-url: https://msp-ext-prd  # TODO: 수정
